# Generated by Django 3.0 on 2021-01-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area_of_specialization',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
