# Generated by Django 3.0 on 2021-01-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbokaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_contact_information',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
