# Generated by Django 3.0 on 2021-01-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbokaapp', '0002_job_company_contact_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Electricity and wiring', 'Electricity and wiring'), ('Welding', 'Welding'), ('Plant operator', 'Plant operator'), ('Plumbing', 'Plumbing'), ('Construction', 'Construction'), ('Painting', 'Painting'), ('Carpentry', 'Carpentry'), ('Sanitation', 'Sanitation'), ('Catering', 'Catering'), ('Gardening', 'gardening'), ('Farm labor', 'Farm labor'), ('Minor labor', 'Minor labor')], max_length=40),
        ),
    ]
